version: "3.8"

services:
  movie_service_postgres:
    container_name: movie_service_postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movie
    ports:
      - "5432:5432"
    volumes:
      - movie_service_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  movie_service_postgres_data:
