spring:
  application:
    name: graphqlandelk
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

grpc:
  client:
    movieSearchService:
      address: "localhost:9090"
      negotiationType: plaintext
server:
  port: 8081
