spring:
  application:
    name: graphqlandelk
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
